name: Build PROCHAN APK

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. جلب المشروع
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. إعطاء صلاحية التنفيذ لملف gradlew
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # 3. إعداد JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution:
